app/controllers/course_notifications_controller.rb
app/mailers/course_notification_mailer.rb
app/mailers/feedback_reply_mailer.rb
app/mailers/review_mailer.rb
config/site.defaults.yml
spec/controllers/feedback_replies_controller_spec.rb

Hopefully this makes recipient servers less likely to flag our e-mails as spam.

All e-mails: put sender in Reply-To instead of From.

---

Changelog.md

Fix year in Changelog

---

Installation.md
README.markdown

Added installation instructions into their own file and added link to README

Refined installation instructions

---

lib/test_run_grader.rb

We don't want this to happen: http://u.tktl.fi/png/e2329b31ce2ee722bc2196b6e1832669

Only give points that are available from the exercise

---

lib/test_run_grader.rb

Reverts testmycode/tmc-server#241

Revert "Only give points that are available from the exercise"

---

Installation.md

Current instructions don't represent all the steps needed

Update installation instructions

---

app/controllers/courses_controller.rb
app/models/exercise.rb
app/models/exercise_group.rb
app/models/uncomputed_unlock.rb
app/models/unlock_spec.rb
app/views/courses/manage_unlocks.erb
app/views/courses/show.html.erb
config/routes.rb
lib/course_refresher.rb
spec/controllers/courses_controller_spec.rb
spec/features/teacher_edits_unlock_dates_spec.rb

Teachers can set unlock dates for courses in gui

Gui unlock date

---

lib/test_run_grader.rb
spec/lib/test_run_grader_spec.rb

We don't want this to happen: http://u.tktl.fi/png/e2329b31ce2ee722bc2196b6e1832669

WIP: Only give points that are available from the exercise

---

app/views/exercises/show.html.erb

I don't know if this should be admin only feature to be able to verify exercise points more easily.

WIP: Show available points from exercise in exercise page

---

app/assets/javascripts/courses.js
app/assets/stylesheets/courses.css
app/assets/stylesheets/main.css
app/controllers/courses_controller.rb
app/models/course.rb
app/models/exercise.rb
app/models/exercise_group.rb
app/views/courses/_deadline_fields.html.erb
app/views/courses/manage_deadlines.html.erb
config/initializers/assets.rb
spec/features/teacher_sets_deadlines_spec.rb
spec/models/course_spec.rb
spec/usermanual/teachers.html.erb

Some tests might fail on this, they are fixed on different branch and will be on another PR. Test concerning these changes should work.

Support for editing single exercise deadlines

---

app/controllers/organizations_controller.rb
app/models/ability.rb
app/views/organizations/show.html.erb
config/routes.rb
db/migrate/20150625081824_add_hidden_to_organization.rb
db/schema.rb
spec/controllers/organizations_controller_spec.rb
spec/features/teacher_creates_organization_spec.rb

Functionality for teachers (and admins) to toggle organization visibility.

Organization hiding

---

app/controllers/submissions_controller.rb

Fast bugfix before leaving office, couldn't run now any tests, or do proper manual testing. Merge carefully, if seems ok :)

fixed paste visibility for course teachers

---

app/controllers/participants_controller.rb
app/models/ability.rb
config/routes.rb
spec/controllers/participants_controller_spec.rb

Add participants/me to view my stats

---

spec/usermanual/admins.html.erb
spec/usermanual/teachers.html.erb
spec/usermanual/usermanual_spec.rb

Fixed user manual generating spec to work again. Also made some brief content updates, to match current status, but especially teacher manual needs closer look and additions later. That's best to update after we have all course options merged.
Whole test set not run for this, but shouldn't break anything. :)

User manual fix

---

app/models/source_file_list.rb
lib/course_refresher.rb
lib/system_commands.rb

and updated get_makefile_points to use SystemCommands.
and change SystemCommands to behave as expected

Show cpp files in files view, use tmc_available_points.txt instead of parsing stdout

---

.travis-update-usermanual.sh
.travis.yml
lib/doc_gen.rb
spec/usermanual/admins.html.erb
spec/usermanual/customcourse.html.erb
spec/usermanual/teachers.html.erb

and move the html files one step up to make paths nicer.
This is ready to merge, but fails in travis because of another [bug](https://github.com/travis-ci/travis-ci/issues/5220)
So let's merge this after the travis issue is solved.

Start autobuilding usermanual

---

app/controllers/organizations_controller.rb
app/views/organizations/_form.html.erb
app/views/organizations/edit.html.erb
app/views/organizations/new.html.erb
config/environments/test.rb
db/migrate/20160309101401_add_contact_details_to_organization.rb
db/schema.rb
spec/spec_helper.rb
spec/usermanual/admins.html.erb
spec/usermanual/teachers.html.erb

First step to improve organization creation.

Added contact details to organization

---

.gitignore
spec/controllers/teachers_controller_spec.rb
spec/features/teacher_adds_new_teacher_spec.rb

Some gitignore updates and removed useless tests.

Small fixes

---

.dockerignore
Dockerfile
README.markdown
common.yml
config/database.docker.yml
config/database.yml
docker-compose.yml
entry.sh
lib/rspec_remote_formatter.rb
spec/spec_helper.rb

Uses for test result collection: https://github.com/jamox/remote_rspec_aggregator

Allow running tests in docker containers

---

app/assets/stylesheets/main.css
app/assets/stylesheets/sessions.css
app/controllers/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/sessions/_login_form.html.erb
app/views/sessions/new.html.erb
config/initializers/assets.rb
spec/controllers/sessions_controller_spec.rb

Make the login screen a bit better so that we don't scare off our OAuth users.

Prettier login screen

---

app/controllers/api/v8/apidocs_controller.rb
app/controllers/api/v8/base_controller.rb
spec/controllers/api/v8/base_controller_spec.rb

Adds the basecontroller to the v8.
This file is used by most (all?) other controllers in the v8.
@testmycode/api-team 
http://ohtu-jenkins.testmycode.io/job/v8basecontroller/4/

Add basecontroller to v8

---

app/controllers/api/v8/exercises_controller.rb

Fix requested by @jamo 
https://github.com/testmycode/tmc-server/pull/450
jenkins build: http://ohtu-jenkins.testmycode.io/job/tmc-server-api-exercise-search/6/

removed unnecessary query

---

app/controllers/api/v8/apidocs_controller.rb
app/controllers/api/v8/base_controller.rb
app/controllers/api/v8/courses_controller.rb
app/controllers/api/v8/exercises_controller.rb
app/controllers/api/v8/submissions_controller.rb
app/controllers/application_controller.rb
app/helpers/authorized_content_helper.rb
app/models/submission.rb
config/routes.rb
spec/controllers/api/v8/courses_controller_spec.rb
spec/controllers/api/v8/exercises_controller_spec.rb
spec/controllers/api/v8/submissions_controller_spec.rb
spec/controllers/v8/submissions_controller_spec.rb

Find all submissions by course id: /api/v8/courses/{course_id}/exercises/submissions
Find all submissions by course name: /api/v8/org/{organization_id}/courses/{course_name}/submissions
Find single user's submissions by course id: /api/v8/courses/{course_id}/exercises/submissions/{user_id}
Find single user's submissions by course name: /api/v8/org/{organization_id}/courses/{course_name}/submissions/{user_id}
Find current user's submissions by course id: /api/v8/courses/{course_id}/exercises/submissions/mine
Find current user's submissions by course name: /api/v8/org/{organization_id}/courses/{course_name}/submissions/mine
closes #434 
closes #433 
closes #436 
closes #435 
closes #438 
closes #437 
Jenkins builds: 
http://ohtu-jenkins.testmycode.io/job/tmc-server-api-submission-search/1/ …

Api find submissions by course name or id

---

app/controllers/api/v8/apidocs_controller.rb
app/controllers/api/v8/courses_controller.rb
app/controllers/api/v8/exercises_controller.rb
app/controllers/api/v8/submissions_controller.rb
app/controllers/application_controller.rb
app/helpers/authorize_collection_helper.rb
app/helpers/authorized_content_helper.rb
app/models/submission.rb
config/routes.rb
spec/controllers/api/v8/exercises_controller_spec.rb
spec/controllers/api/v8/submissions_controller_spec.rb

closes #401 
Jenkins build: http://ohtu-jenkins.testmycode.io/job/tmc-server-api-exercises-download/13/

Api exercises download without authentication

---

app/controllers/api/v8/apidocs_controller.rb
app/controllers/api/v8/core/organizations/courses_controller.rb
app/controllers/api/v8/organizations/courses/exercises/points_controller.rb
app/controllers/api/v8/organizations/courses/exercises/users/points_controller.rb
app/controllers/api/v8/organizations/courses/exercises_controller.rb
app/controllers/api/v8/organizations/courses/points_controller.rb
app/controllers/api/v8/organizations/courses/submissions_controller.rb
app/controllers/api/v8/organizations/courses/users/points_controller.rb
app/controllers/api/v8/organizations/courses/users/submissions_controller.rb
app/controllers/api/v8/organizations/courses_controller.rb
app/controllers/api/v8/organizations_controller.rb
app/models/organization.rb
config/routes.rb

Endpoint for api v8 that show's one organization's information as json

Organization json

---

app/controllers/api/v8/users_controller.rb

- Update password if parameters old_password, password and password_repeat are added to request
- Update email if it differs from the current email
- If email is updated, flag "email_verified" is set to false
- Try to save changes only if there are no validation errors

Bs4 update password and email

---

app/controllers/results_controller.rb

Should be implemented before https://github.com/rage/sandbox is in use.

New sandbox result handling

---

lib/sandbox_results_saver.rb

Merge before Rails 6 to production

all_tests_passed false, if error encountered

---

app/controllers/setup/course_details_controller.rb
app/helpers/application_helper.rb
app/models/course.rb
app/views/courses/show.html.erb
app/views/setup/course_details/edit.html.erb
app/views/setup/course_details/new.html.erb
config/locales/en.yml

* Added a field for the id in course creation and edit
* Added a bullet point to the teacher-section of course information

Enable MOOC.fi id customization from web ui

---

app/controllers/api/v8/core/exercises/details_controller.rb
app/models/exercise.rb
spec/integration/destroying_user_spec.rb

Downloading exercises that hides submission returns 403.

Expose if course or exercise hides submission

---

app/controllers/submissions_controller.rb
app/models/course.rb
app/models/exercise.rb

Add a paste visibility option where a paste is visible only if the student has completed the exercise themselves

Add paste visibility option for completed only
